[package]
name = "min-book"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Maycon F. Melo <@mayconfmelo>"]
license = "MIT-0"
description = "Simple and complete books without introducing new sintax"
categories = [ "layout", "book" ]
keywords = [ "book", "document structuring" ]
repository = "https://github.com/mayconfmelo/min-book"
exclude = [
  "dev/",
  "test/",
  "docs/",
  "scripts/",
  ".git",
  ".gitignore",
  "justfile"
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "/docs/assets/thumbnail.png"
  